name: 🚀 Feature Suggestion | Feature Request
title: "🚀 Feature: Description"
description: Suggest ideas for new features of the project
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to Solve
      description: What problem did you run into while using the project that calls for a new feature?
    validations:
      required: true

  - type: textarea
    id: feature
    attributes:
      label: Describe the Desired Feature
      description: Please describe the desired feature or solution
    validations:
      required: true
